name: Check-out

on:
  schedule:
    - cron: "0 11 * * 1,5"
    - cron: "3 11 * * 2,3"
    - cron: "7 11 * * 4"
  workflow_dispatch:

jobs:

  get-last-success-time:
    runs-on: ubuntu-latest
    outputs:
      last_success_time: ${{ steps.set-time.outputs.time }}
    steps:
      - name: Get last success time of check-in.yml
        id: set-time
        run: |
          # Use GitHub API to get the last successful run time of check-in.yml
          TIME=$(curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/actions/workflows/check-in.yml/runs?status=success | jq '.workflow_runs[0].created_at')
          echo "Last successful check-in time: $TIME"
          echo "::set-output name=time::$TIME"

  check-out:
    needs: get-last-success-time
    env:
      ACCOUNT_EMAIL: ${{ secrets.ACCOUNT_EMAIL }}
      ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
      GEO_LATITUDE: ${{ secrets.GEO_LATITUDE }}
      GEO_LONGITUDE: ${{ secrets.GEO_LONGITUDE }}
      CHECK_TYPE: "CHECK_OUT"
    runs-on: ubuntu-latest
    steps:
      - name: Wait if necessary
        run: |
          # Implement logic to compute the time difference and delay execution if necessary
          # Pseudo-code:
          # CURRENT_TIME = current UTC time
          # DIFF = CURRENT_TIME - get-last-success-time.outputs.last_success_time
          # if DIFF < 9 hours:
          #     sleep for (9 hours - DIFF)

      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Checking Out
        run: node index.js
